- name: Enable epel-release
  yum: name=epel-release state=present

- name: opendkim packages are installed
  yum: name={{ item }} state=present
  with_items:
   - opendkim
#   - opendkim-tools

- name: opendkim socket configured
  lineinfile: dest=/etc/opendkim.conf regexp=^SOCKET= line='SOCKET="inet:8891@localhost"'
  notify:
    - systemctl restart opendkim

- name: opendkim directory present
  file: path=/etc/opendkim state=directory
  file: path=/etc/opendkim/keys state=directory

- name: opendkim TrustedHosts present
  copy: src=TrustedHosts dest=/etc/opendkim/TrustedHosts
  notify:
    - systemctl restart opendkim

- name: opendkim is configured
  template: src=opendkim.conf.j2 dest=/etc/opendkim.conf
#  notify:
#    - restart opendkim

- name: opendkim KeyTable is configured
  template: src=KeyTable.j2 dest=/etc/opendkim/KeyTable
  notify:
    - systemctl restart opendkim

- name: opendkim SigningTable is configured
  template: src=SigningTable.j2 dest=/etc/opendkim/SigningTable
  notify:
    - systemctl restart opendkim

- name: Generate signing key
  command: "{{ opendkim_opendkim_genkey_path }} -s {{ dkim_selector }} -d {{ mydomain[0] }} -D /etc/opendkim/keys"
  args:
    creates: "/etc/opendkim/keys/{{ dkim_selector }}.private"
    warn: false
  notify:
    - restart opendkim

- name: Opendkim signing key file ownership
  file:
    path: "/etc/opendkim/keys/{{ dkim_selector }}.private"
    owner: opendkim
    group: opendkim

#- name: ensure signing key is present
#  file: path=/etc/opendkim/keys/{{ item.key }} owner=opendkim group=opendkim
#  with_items: "{{ mydomain }}"
#  notify:
#    - systemctl restart opendkim

#- name: chown and chmod /etc/opendkim
#  file: path=/etc/opendkim state=directory owner=opendkim group=opendkim recurse=yes
#  notify:
#    - systemctl restart opendkim

- name: opendkim is running
  service: name=opendkim state=restarted enabled=yes

- name: Restart postfix and enable it on startup
  service: name=postfix state=restarted enabled=yes
