- name: Install psycopg2
  pip:
    name: psycopg2-binary
    state: present
  become: yes

- name: Install psycopg2 for python3
  pip:
    name: psycopg2-binary
    state: present
    executable: /bin/pip2
  become: yes
